const data = [
    {
      planet: "Luna",
      description: "La Luna, aunque no es un planeta, es un cuerpo celeste fundamental. Orbita alrededor de la Tierra y, al ser nuestro satélite natural más cercano, influye en mareas y ciclos terrestres. Con temperaturas extremas que oscilan entre los 127°C (261°F) durante el día y -173°C (-280°F) por la noche, su superficie presenta características únicas y ha sido un objetivo de exploración espacial desde hace décadas.",
      source: "https://es.wikipedia.org/wiki/Luna",
      overview: "images/mercury/planet-mercury.svg",
      internalStructure: "images/mercury/planet-mercury-internal.svg",
      surfaceGeology: "images/mercury/geology-mercury.png",
      rotationTime: "27.3 dias",
      revolutionTime: "27.3 dias",
      radius: "1,737.4 KM",
      averageTemperature: "-23°C",
    },
  
    {
      planet: "Marte",
      description: "Marte es el cuarto planeta desde el Sol y el segundo más pequeño del Sistema Solar, siendo más grande que Mercurio solamente. En inglés, Marte lleva el nombre del dios romano de la guerra y a menudo se le conoce como el 'Planeta Rojo'.",
      source: "https://es.wikipedia.org/wiki/Marte_(planeta)",
      overview: "images/mars/planet-mars.svg",
      internalStructure: "images/mars/planet-mars-internal.svg",
      surfaceGeology: "images/mars/geology-mars.png",
      rotationTime: "24.6 horas",
      revolutionTime: " 687 días",
      radius: "3.389,5 KM",
      averageTemperature: "-28°C",
    },
  
    {
      planet: "Júpiter",
      description: "Júpiter es el quinto planeta desde el Sol y el más grande del Sistema Solar. Es un gigante gaseoso con una masa dos veces y media mayor que la de todos los demás planetas combinados, pero menos de una milésima parte de la masa del Sol.",
      source: "https://es.wikipedia.org/wiki/J%C3%BApiter_(planeta)",
      overview: "images/jupiter/planet-jupiter.svg",
      internalStructure: "images/jupiter/planet-jupiter-internal.svg",
      surfaceGeology: "images/jupiter/geology-jupiter.png",
      rotationTime: "9.93 horas",
      revolutionTime: "11.86 años",
      radius: "69.911 KM",
      averageTemperature: "-108°C",
    },
  
    {
      planet: "Saturno",
      description: "Saturno es el sexto planeta desde el Sol y el segundo más grande del Sistema Solar después de Júpiter. Es un gigante gaseoso con un radio promedio de aproximadamente nueve veces y media el de la Tierra. Tiene solo un octavo de la densidad promedio de la Tierra.",
      source: "https://es.wikipedia.org/wiki/Saturno_(planeta)",
      overview: "images/saturn/planet-saturn.svg",
      internalStructure: "images/saturn/planet-saturn-internal.svg",
      surfaceGeology: "images/saturn/geology-saturn.png",
      rotationTime: "10.7 horas",
      revolutionTime: "29.5 años",
      radius: "58.232 KM",
      averageTemperature: "-138°C",
    },
  
    {
      planet: "Urano",
      description: "Urano es el séptimo planeta desde el Sol. Su nombre hace referencia al dios griego del cielo; según la mitología griega, Urano era el bisabuelo de Ares. Tiene el tercer radio planetario más grande y la cuarta mayor masa planetaria en el Sistema Solar.",
      source: "https://es.wikipedia.org/wiki/Urano_(planeta)",
      overview: "images/uranus/planet-uranus.svg",
      internalStructure: "images/uranus/planet-uranus-internal.svg",
      surfaceGeology: "images/uranus/geology-uranus.png",
      rotationTime: "17.2 horas",
      revolutionTime: "84 años",
      radius: "25.362 km",
      averageTemperature: "-195°C",
    },
  
    {
      planet: "Netuno",
      description: "Neptuno es el octavo y más distante planeta conocido del Sol. En el Sistema Solar, es el cuarto planeta más grande en diámetro, el tercero más masivo y el planeta gigante más denso. Es 17 veces la masa de la Tierra, más masivo que su casi gemelo Urano.",
      source: "https://es.wikipedia.org/wiki/Neptuno_(planeta)",
      overview: "images/neptune/planet-neptune.svg",
      internalStructure: "images/neptune/planet-neptune-internal.svg",
      surfaceGeology: "images/neptune/geology-neptune.png",
      rotationTime: "16.08 horas",
      revolutionTime: "164.79 años",
      radius: "24.622 KM",
      averageTemperature: "-201°C",
    },
  ];